### ISSUE TITLE
不能重現開發環境

### ISSUE THREAD

**Issue by larrykkk** [shihua-guo/vue-gis#1]
我把整個專案 clone 下來以後   
先下npm install   
然後  npm run dev   
報錯 
Error: Cannot find module 'C:\Users\blueplanet\Desktop\vue-gis\build\dev-server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-vue@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-vue@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\blueplanet\AppData\Roaming\npm-cache\_logs\2019-04-22T06_09_09_931Z-debug.log

看起來像是沒有找到 build\dev-server.js 這裡的檔案 請問是不是可以告訴我怎麼重現開發環境呢

**Comment by larrykkk** [comment]
我在 [官方github](https://github.com/Esri/esri-loader) 找到的[範例](https://github.com/tomwayson/esri-vue-cli-example)
